spring:
  application:
    name: springai
  data:
    redis:
      client-type: jedis
      url:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        model: qwen-plus
      embedding:
        model: text-embedding-v4 #阿里的文本向量模型
        dimensions: 2048 #向量维度
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen
logging:
  level:
    org.springframework.ai: debug